-- 01_prompts_en_rollback.sql - puts back the Russian texts saved by 01_prompts_en.sql (tables tes_backup_ru_*).
-- GENERATED by settings/en/build_sql.php.
--   psql -U dwemer -d dwemer -v ON_ERROR_STOP=1 -f settings/en/01_prompts_en_rollback.sql
-- Fails (and changes nothing) if a backup table is missing, i.e. if the apply file never ran.
-- The backup tables are kept, so apply and rollback can be repeated.
\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';
BEGIN;

-- prompts: all 61 Russian custom_prompt values (steps 3 and 4)
UPDATE public.prompts p SET custom_prompt = b.custom_prompt, updated_at = b.updated_at
FROM public.tes_backup_ru_prompts b
WHERE b.prompt_key = p.prompt_key AND p.custom_prompt IS DISTINCT FROM b.custom_prompt;

-- NPC prompt head (step 5)
UPDATE public.general_settings g SET value = b.value, updated_at = b.updated_at
FROM public.tes_backup_ru_general_settings b
WHERE b.id = g.id AND g.value IS DISTINCT FROM b.value;

-- Narrator (step 6)
UPDATE public.core_narrator n SET value = b.value
FROM public.tes_backup_ru_core_narrator b
WHERE b.id = n.id AND n.value IS DISTINCT FROM b.value;

-- Diary instruction (step 7)
UPDATE public.core_profiles p SET metadata = jsonb_set(p.metadata, '{DIARY_PROMPT}', to_jsonb(b.diary_prompt))
FROM public.tes_backup_ru_core_profiles b
WHERE b.id = p.id AND b.diary_prompt IS NOT NULL AND p.metadata->>'DIARY_PROMPT' IS DISTINCT FROM b.diary_prompt;

SELECT 'prompts: custom rows / with Cyrillic letters' AS what, count(custom_prompt)::text || ' / ' || count(*) FILTER (WHERE custom_prompt ~ '[А-Яа-яЁё]')::text AS value FROM public.prompts
UNION ALL SELECT 'PROMPT_HEAD: chars / Cyrillic letters', length(value)::text || ' / ' || length(regexp_replace(value, '[^А-Яа-яЁё]', '', 'g'))::text FROM public.general_settings WHERE id = 'PROMPT_HEAD'
UNION ALL SELECT 'narrator ' || id || ': chars / Cyrillic letters', length(value)::text || ' / ' || length(regexp_replace(value, '[^А-Яа-яЁё]', '', 'g'))::text FROM public.core_narrator WHERE id IN ('prompt_head', 'background', 'personality', 'speechstyle', 'goals')
UNION ALL SELECT 'DIARY_PROMPT: chars / Cyrillic letters', length(metadata->>'DIARY_PROMPT')::text || ' / ' || length(regexp_replace(metadata->>'DIARY_PROMPT', '[^А-Яа-яЁё]', '', 'g'))::text FROM public.core_profiles WHERE metadata ? 'DIARY_PROMPT';

COMMIT;

-- After a rollback you are sure about, the backups may be dropped by hand:
-- DROP TABLE public.tes_backup_ru_prompts, public.tes_backup_ru_general_settings, public.tes_backup_ru_core_narrator,
--            public.tes_backup_ru_core_profiles;
