<?php
/*
 * Builds 01_prompts_en.sql and 01_prompts_en_rollback.sql from the .txt files of this directory.
 *   php settings/en/build_sql.php
 * It only reads the .txt files and writes the two .sql files; it never connects to the database.
 * Edit a text -> run this again -> review the diff of the .sql files. See README.md.
 */
$dir = __DIR__ . '/';

/** Text of a file without the final line break (trailing spaces are kept: ai_vision_appearance ends with one). */
function txt(string $path): string
{
    $s = file_get_contents($path);
    if ($s === false) {
        fwrite(STDERR, "cannot read {$path}\n");
        exit(1);
    }
    $s = str_replace("\r\n", "\n", $s);
    $s = rtrim($s, "\n");
    if (strpos($s, '$tes$') !== false) {
        fwrite(STDERR, "{$path} contains the quote tag \$tes\$\n");
        exit(1);
    }
    return $s;
}

function q(string $s): string
{
    return '$tes$' . $s . '$tes$';
}

// md5 of the Russian texts the English ones were translated from (live database, 2026-10-09).
// The apply file stops if the live text is neither this nor the English one: somebody edited it since.
$ruMd5 = [
    'PROMPT_HEAD'          => '3d04488a796634d0f98e60df976b9e66',
    'narrator_prompt_head' => '9d3f228daab3f03a7cfe5a2a6f6b0c4a',
];

// 46 keys: custom_prompt is a plain translation of default_prompt -> NULL brings the English default back.
$toNull = [
    'background_life_innerthought', 'background_life_letter', 'book_summary_prompt',
    'dialogue_line_inline_response', 'dialogue_line_inline_response_narrator', 'dialogue_line_inline_response_npc',
    'dialogue_line_response',
    'directorSuggestionSystem', 'director_bored_event_rules', 'director_bored_event_system_prompt',
    'director_examples_prompt', 'director_instruction_rules', 'director_system_prompt',
    'inline_narration_prompt', 'inline_narration_prompt_narrator', 'inline_narration_prompt_npc',
    'memory_subsystem_summary', 'middleterm_narrative_summarizer',
    'narrator_bored_prompt', 'narrator_welcome_prompt', 'player_diary_prompt',
    'player_mood_angry_prompt', 'player_mood_annoyed_prompt', 'player_mood_confused_prompt', 'player_mood_custom_prompt',
    'player_mood_flirty_prompt', 'player_mood_happy_prompt', 'player_mood_playful_prompt', 'player_mood_sad_prompt',
    'player_mood_scared_prompt', 'player_mood_surprised_prompt', 'player_mood_suspicious_prompt',
    'player_respeech_output_prompt', 'player_respeech_output_strip_prompt',
    'player_respeech_rewrite_prompt', 'player_respeech_rewrite_strip_prompt',
    'quest_comment_prompt', 'random_narration_prompt',
    'rechat_listener_prompt_relaxed', 'rechat_listener_prompt_strict',
    'rechat_response_prompt_relaxed_1', 'rechat_response_prompt_relaxed_2', 'rechat_response_prompt_relaxed_3',
    'rechat_response_prompt_strict_1', 'rechat_response_prompt_strict_2', 'rechat_response_prompt_strict_3',
];

// 15 keys: requests without the prompt head (or with Russian examples that matter) -> English text from prompts/<key>.txt.
$custom = [
    'ai_vision_appearance', 'character_profile_generation', 'custom_oghma',
    'dynamic_prompt_goals', 'dynamic_prompt_occupation', 'dynamic_prompt_personality',
    'dynamic_prompt_relationships', 'dynamic_prompt_skills', 'dynamic_prompt_speechstyle',
    'middleterm_narrative_request', 'player_speech_style_prompt',
    'rel_llm_analysis', 'rel_llm_evaluation', 'rel_llm_npc_to_npc', 'summary_prompt',
];
if (count($toNull) !== 46 || count($custom) !== 15 || array_intersect($toNull, $custom)) {
    fwrite(STDERR, 'key lists are wrong: ' . count($toNull) . ' + ' . count($custom) . "\n");
    exit(1);
}

$head = txt($dir . 'prompt_head_en.txt');
$narr = [
    'prompt_head' => txt($dir . 'narrator_prompt_head_en.txt'),
    'background'  => txt($dir . 'narrator_background_en.txt'),
    'personality' => txt($dir . 'narrator_personality_en.txt'),
    'speechstyle' => txt($dir . 'narrator_speechstyle_en.txt'),
    'goals'       => txt($dir . 'narrator_goals_en.txt'),
];
$diary = txt($dir . 'diary_prompt_en.txt');
// the placeholders the Russian texts had must still be there
$need = [
    ['#HERIKA_NAME#', $head], ['#PLAYER_NAME#', $narr['prompt_head']], ['#PLAYER_NAME#', $narr['goals']],
    ['#HERIKA_NAME#', $diary], ['#PLAYER_NAME#', $diary],
];
foreach ($need as [$ph, $text]) {
    if (strpos($text, $ph) === false) {
        fwrite(STDERR, "placeholder {$ph} is missing\n");
        exit(1);
    }
}

$inList = fn(array $keys) => "'" . implode("',\n    '", $keys) . "'";
$allKeys = array_merge($toNull, $custom);
sort($allKeys);

$a = [];
$a[] = '-- 01_prompts_en.sql - prompt texts stored in the database go back to English; NPCs keep answering in Russian.';
$a[] = '-- GENERATED by settings/en/build_sql.php from the .txt files next to it - edit those, not this file.';
$a[] = '-- Apply (after the owner said yes):  psql -U dwemer -d dwemer -v ON_ERROR_STOP=1 -f settings/en/01_prompts_en.sql';
$a[] = '-- Undo:                              psql -U dwemer -d dwemer -v ON_ERROR_STOP=1 -f settings/en/01_prompts_en_rollback.sql';
$a[] = '-- One transaction: either every step is applied or none. Safe to run twice (the backups are made once).';
$a[] = '\set ON_ERROR_STOP on';
$a[] = "SET client_encoding = 'UTF8';";
$a[] = 'BEGIN;';
$a[] = '';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = '-- Step 1. Backups of the Russian texts. IF NOT EXISTS: a second run keeps the first (Russian) copy.';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = 'CREATE TABLE IF NOT EXISTS public.tes_backup_ru_prompts AS';
$a[] = '    SELECT prompt_key, custom_prompt, updated_at, now() AS saved_at FROM public.prompts;';
$a[] = 'CREATE TABLE IF NOT EXISTS public.tes_backup_ru_general_settings AS';
$a[] = "    SELECT id, value, updated_at, now() AS saved_at FROM public.general_settings WHERE id = 'PROMPT_HEAD';";
$a[] = 'CREATE TABLE IF NOT EXISTS public.tes_backup_ru_core_narrator AS';
$a[] = "    SELECT id, value, now() AS saved_at FROM public.core_narrator WHERE id IN ('prompt_head', 'background', 'personality', 'speechstyle', 'goals');";
$a[] = 'CREATE TABLE IF NOT EXISTS public.tes_backup_ru_core_profiles AS';
$a[] = "    SELECT id, metadata->>'DIARY_PROMPT' AS diary_prompt, now() AS saved_at FROM public.core_profiles WHERE metadata ? 'DIARY_PROMPT';";
$a[] = '';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = '-- Step 2. Guard: stop if a prompt head was edited after the English text was written from it';
$a[] = '-- (a rule added in the CHIM UI or by a fix script would silently disappear otherwise).';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = 'DO $guard$';
$a[] = 'DECLARE';
$a[] = '    h text; n text; k int;';
$a[] = 'BEGIN';
$a[] = "    SELECT md5(value) INTO h FROM public.general_settings WHERE id = 'PROMPT_HEAD';";
$a[] = "    IF h IS NULL OR h NOT IN ('" . $ruMd5['PROMPT_HEAD'] . "', '" . md5($head) . "') THEN";
$a[] = "        RAISE EXCEPTION 'general_settings.PROMPT_HEAD changed since settings/en was prepared (md5 %): translate the change into prompt_head_en.txt, update build_sql.php, rebuild', h;";
$a[] = '    END IF;';
$a[] = "    SELECT md5(value) INTO n FROM public.core_narrator WHERE id = 'prompt_head';";
$a[] = "    IF n IS NULL OR n NOT IN ('" . $ruMd5['narrator_prompt_head'] . "', '" . md5($narr['prompt_head']) . "') THEN";
$a[] = "        RAISE EXCEPTION 'core_narrator.prompt_head changed since settings/en was prepared (md5 %): translate the change into narrator_prompt_head_en.txt, update build_sql.php, rebuild', n;";
$a[] = '    END IF;';
$a[] = '    SELECT count(*) INTO k FROM public.prompts WHERE prompt_key IN (';
$a[] = '    ' . $inList($allKeys) . ');';
$a[] = '    IF k <> 61 THEN';
$a[] = "        RAISE EXCEPTION 'expected 61 prompt keys, found % (a CHIM update renamed or removed prompts)', k;";
$a[] = '    END IF;';
$a[] = 'END';
$a[] = '$guard$;';
$a[] = '';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = '-- Step 3. ' . count($toNull) . ' prompts: the Russian custom_prompt is a plain translation -> NULL = English default_prompt.';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = 'UPDATE public.prompts SET custom_prompt = NULL, updated_at = now()';
$a[] = 'WHERE custom_prompt IS NOT NULL AND prompt_key IN (';
$a[] = '    ' . $inList($toNull) . ');';
$a[] = '';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = '-- Step 4. ' . count($custom) . ' prompts: English text that keeps what the Russian one did (Russian output of a request';
$a[] = '-- that has no prompt head, Russian examples). Texts: settings/en/prompts/<key>.txt';
$a[] = '-- ---------------------------------------------------------------------------------------------';
foreach ($custom as $key) {
    $a[] = 'UPDATE public.prompts SET custom_prompt = ' . q(txt($dir . 'prompts/' . $key . '.txt')) . ', updated_at = now()';
    $a[] = "WHERE prompt_key = '{$key}';";
    $a[] = '';
}
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = '-- Step 5. NPC prompt head (<roleplay_instructions> of every NPC request). Text: prompt_head_en.txt';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = 'UPDATE public.general_settings SET value = ' . q($head) . ', updated_at = now()';
$a[] = "WHERE id = 'PROMPT_HEAD';";
$a[] = '';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = '-- Step 6. Narrator: prompt head and the four profile fields that go into every Narrator request.';
$a[] = '-- ---------------------------------------------------------------------------------------------';
foreach ($narr as $id => $text) {
    $a[] = 'UPDATE public.core_narrator SET value = ' . q($text);
    $a[] = "WHERE id = '{$id}';";
    $a[] = '';
}
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = '-- Step 7. Diary instruction of the profile (core_profiles.metadata.DIARY_PROMPT). Text: diary_prompt_en.txt';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = "UPDATE public.core_profiles SET metadata = jsonb_set(metadata, '{DIARY_PROMPT}', to_jsonb(" . q($diary) . '::text))';
$a[] = "WHERE metadata ? 'DIARY_PROMPT' AND metadata->>'DIARY_PROMPT' ~ '[А-Яа-яЁё]';";
$a[] = '';
$a[] = '-- The Russian descriptions of the actions God_Command and Write_Document (core_action) are NOT handled';
$a[] = '-- here: settings/en/02_data_en.sql restores them and seeds its display cache from the Russian text.';
$a[] = '';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = '-- Check (read the output before trusting the COMMIT line): expected values are in README.md.';
$a[] = '-- ---------------------------------------------------------------------------------------------';
$a[] = "SELECT 'prompts: custom rows / with Cyrillic letters' AS what, count(custom_prompt)::text || ' / ' || count(*) FILTER (WHERE custom_prompt ~ '[А-Яа-яЁё]')::text AS value FROM public.prompts";
$a[] = "UNION ALL SELECT 'PROMPT_HEAD: chars / Cyrillic letters', length(value)::text || ' / ' || length(regexp_replace(value, '[^А-Яа-яЁё]', '', 'g'))::text FROM public.general_settings WHERE id = 'PROMPT_HEAD'";
$a[] = "UNION ALL SELECT 'narrator ' || id || ': chars / Cyrillic letters', length(value)::text || ' / ' || length(regexp_replace(value, '[^А-Яа-яЁё]', '', 'g'))::text FROM public.core_narrator WHERE id IN ('prompt_head', 'background', 'personality', 'speechstyle', 'goals')";
$a[] = "UNION ALL SELECT 'DIARY_PROMPT: chars / Cyrillic letters', length(metadata->>'DIARY_PROMPT')::text || ' / ' || length(regexp_replace(metadata->>'DIARY_PROMPT', '[^А-Яа-яЁё]', '', 'g'))::text FROM public.core_profiles WHERE metadata ? 'DIARY_PROMPT';";
$a[] = '';
$a[] = 'COMMIT;';
file_put_contents($dir . '01_prompts_en.sql', implode("\n", $a) . "\n");

$r = [];
$r[] = '-- 01_prompts_en_rollback.sql - puts back the Russian texts saved by 01_prompts_en.sql (tables tes_backup_ru_*).';
$r[] = '-- GENERATED by settings/en/build_sql.php.';
$r[] = '--   psql -U dwemer -d dwemer -v ON_ERROR_STOP=1 -f settings/en/01_prompts_en_rollback.sql';
$r[] = '-- Fails (and changes nothing) if a backup table is missing, i.e. if the apply file never ran.';
$r[] = '-- The backup tables are kept, so apply and rollback can be repeated.';
$r[] = '\set ON_ERROR_STOP on';
$r[] = "SET client_encoding = 'UTF8';";
$r[] = 'BEGIN;';
$r[] = '';
$r[] = '-- prompts: all 61 Russian custom_prompt values (steps 3 and 4)';
$r[] = 'UPDATE public.prompts p SET custom_prompt = b.custom_prompt, updated_at = b.updated_at';
$r[] = 'FROM public.tes_backup_ru_prompts b';
$r[] = 'WHERE b.prompt_key = p.prompt_key AND p.custom_prompt IS DISTINCT FROM b.custom_prompt;';
$r[] = '';
$r[] = '-- NPC prompt head (step 5)';
$r[] = 'UPDATE public.general_settings g SET value = b.value, updated_at = b.updated_at';
$r[] = 'FROM public.tes_backup_ru_general_settings b';
$r[] = 'WHERE b.id = g.id AND g.value IS DISTINCT FROM b.value;';
$r[] = '';
$r[] = '-- Narrator (step 6)';
$r[] = 'UPDATE public.core_narrator n SET value = b.value';
$r[] = 'FROM public.tes_backup_ru_core_narrator b';
$r[] = 'WHERE b.id = n.id AND n.value IS DISTINCT FROM b.value;';
$r[] = '';
$r[] = '-- Diary instruction (step 7)';
$r[] = "UPDATE public.core_profiles p SET metadata = jsonb_set(p.metadata, '{DIARY_PROMPT}', to_jsonb(b.diary_prompt))";
$r[] = 'FROM public.tes_backup_ru_core_profiles b';
$r[] = "WHERE b.id = p.id AND b.diary_prompt IS NOT NULL AND p.metadata->>'DIARY_PROMPT' IS DISTINCT FROM b.diary_prompt;";
$r[] = '';
$r[] = "SELECT 'prompts: custom rows / with Cyrillic letters' AS what, count(custom_prompt)::text || ' / ' || count(*) FILTER (WHERE custom_prompt ~ '[А-Яа-яЁё]')::text AS value FROM public.prompts";
$r[] = "UNION ALL SELECT 'PROMPT_HEAD: chars / Cyrillic letters', length(value)::text || ' / ' || length(regexp_replace(value, '[^А-Яа-яЁё]', '', 'g'))::text FROM public.general_settings WHERE id = 'PROMPT_HEAD'";
$r[] = "UNION ALL SELECT 'narrator ' || id || ': chars / Cyrillic letters', length(value)::text || ' / ' || length(regexp_replace(value, '[^А-Яа-яЁё]', '', 'g'))::text FROM public.core_narrator WHERE id IN ('prompt_head', 'background', 'personality', 'speechstyle', 'goals')";
$r[] = "UNION ALL SELECT 'DIARY_PROMPT: chars / Cyrillic letters', length(metadata->>'DIARY_PROMPT')::text || ' / ' || length(regexp_replace(metadata->>'DIARY_PROMPT', '[^А-Яа-яЁё]', '', 'g'))::text FROM public.core_profiles WHERE metadata ? 'DIARY_PROMPT';";
$r[] = '';
$r[] = 'COMMIT;';
$r[] = '';
$r[] = '-- After a rollback you are sure about, the backups may be dropped by hand:';
$r[] = '-- DROP TABLE public.tes_backup_ru_prompts, public.tes_backup_ru_general_settings, public.tes_backup_ru_core_narrator,';
$r[] = '--            public.tes_backup_ru_core_profiles;';
file_put_contents($dir . '01_prompts_en_rollback.sql', implode("\n", $r) . "\n");

echo 'NULL keys: ' . count($toNull) . ', custom keys: ' . count($custom) . "\n";
echo 'md5 PROMPT_HEAD en: ' . md5($head) . "\n";
echo 'md5 narrator prompt_head en: ' . md5($narr['prompt_head']) . "\n";
echo "written: 01_prompts_en.sql, 01_prompts_en_rollback.sql\n";
