"""Put the modpack author's plugin order back (profile backup from before the 3BA work), new plugins at the end.
Waits until MO2 and the game are closed - MO2 rewrites these files when it exits."""
import io, os, shutil, subprocess, sys, time
P = r'G:\SteamLibrary\steamapps\common\Skyrim Special Edition\MO2\profiles\RFAD_SE'
dry = '--dry' in sys.argv

def running():
    out = subprocess.run(['tasklist'], capture_output=True, text=True).stdout.lower()
    return [n for n in ('modorganizer.exe', 'skyrimse.exe') if n in out]

def read(p):
    return [l.rstrip('\r\n') for l in io.open(p, encoding='utf-8')]

if not dry:
    t0 = time.time()
    while running():
        time.sleep(5)
        if time.time() - t0 > 3 * 3600:
            print('gave up waiting'); sys.exit(1)
    time.sleep(3)

base = [l.strip() for l in read(P + r'\loadorder.txt.bak-before-3ba') if l.strip() and not l.startswith('#')]
cur_lo = [l.strip() for l in read(P + r'\loadorder.txt') if l.strip() and not l.startswith('#')]
cur_pl = read(P + r'\plugins.txt')
active = {l.lstrip('*').strip().lower() for l in cur_pl if l.startswith('*')}
known = {l.lstrip('*').strip().lower(): l.lstrip('*').strip() for l in cur_pl if l.strip() and not l.startswith('#')}
exists = {n.lower() for n in cur_lo} | set(known)
order, seen = [], set()
for n in base:
    if n.lower() in exists and n.lower() not in seen:
        order.append(n); seen.add(n.lower())
added = []
for n in cur_lo + list(known.values()):
    if n.lower() not in seen:
        order.append(n); seen.add(n.lower()); added.append(n)
print('plugins', len(order), '| new at the end:', added)
print('first 12 :', order[:12])
if dry and not os.environ.get('ORDER_OUT'):
    sys.exit(0)
OUT = os.environ.get('ORDER_OUT')
stamp = time.strftime('%Y%m%d-%H%M')
if not OUT:
  for f in ('loadorder.txt', 'plugins.txt'):
    shutil.copy2(os.path.join(P, f), os.path.join(P, f + '.bak-loot-order-' + stamp))
io.open((OUT or P) + r'\loadorder.txt', 'w', encoding='utf-8', newline='\r\n').write('# This file was automatically generated by Mod Organizer.\n' + '\n'.join(order) + '\n')
official = {'skyrim.esm', 'update.esm', 'dawnguard.esm', 'hearthfires.esm', 'dragonborn.esm'}
lines = ['# This file was automatically generated by Mod Organizer.']
for n in order:
    if n.lower() in official or n.lower() not in known:
        continue  # implicit (official / Creation Club) plugins are not listed in plugins.txt
    lines.append(('*' if n.lower() in active else '') + n)
io.open((OUT or P) + r'\plugins.txt', 'w', encoding='utf-8', newline='\r\n').write('\n'.join(lines) + '\n')
print('applied; backups *.bak-loot-order-' + stamp)
